### ISSUE TITLE
Предложение по работе отрисовщика

### ISSUE THREAD

**Issue by DaddyWesker** [onemoreworld/stt#1]
В общем, Олег меня попросил продублировать проблему здесь, на GitHub'e.

Просьба сделать так, чтобы движения мышкой не влияли на отрисовщик: не крутилась постоянно камера, а была как бы закреплена, а при нажатии на лкм, к примеру, уже можно было крутить-вертеть.

**Comment by elevir** [comment]
@DaddyWesker добавлена возможность вращения камеры только при зажатой левой кнопке мыши.
