### ISSUE TITLE
Проблемы при получении неверных данных

### ISSUE THREAD

**Issue by DaddyWesker** [onemoreworld/stt#2]
В общем, тестировал тут получение вращения и сдвига через гомографию и столкнулся со следующей проблемой. У меня в один момент могут подаваться неверные данные (NAN), рисовалка зависает (ну в смысле сама продолжает работать, но больше ничего не отрисовывает, даже если я прерываю свою отсылающую программу и посылаю заведомо верные значения). Даже если нажать кнопку Reset не получается заставить рисовалку чертить путь снова. Помогает лишь перезапуск exe-шки. Можно ли с этим что-то сделать?

И второе - кнопка points visibility такое ощущение, что ничего не делает. Может я не прав конечно.

**Comment by elevir** [comment]
@DaddyWesker поведение при мусорных входных данных исправлено.
Требуется уточнение по точкам. В пакете также содержатся обнаруженные ключевые точки? Данная кнопка относится к отображению облака точек, если точек во входном пакете нет, то эта кнопка действительно бесполезна.

**Comment by DaddyWesker** [comment]
Хм. То есть это для отрисовки облака точек? тогда ясно. Нет, не находятся. Благодарю.
exe-шку здесь качнуть можно где-то?

**Comment by elevir** [comment]
@DaddyWesker сейчас откомпилирую и отправлю :)
