### ISSUE TITLE
Проблема с отображением угла

### ISSUE THREAD

**Issue by DaddyWesker** [onemoreworld/stt#3]
Столкнулись сегодня со следующей бедой. В рисовалку подаётся кватернион вида 
w = 1.0
x = 8.32e-17
y = 4.16e-17
z = 1.38e-17
То есть, по сути, нулевое вращение (просто держим камеру статично и смотрим что происходит в статике). Грешили на методы разложения существенной матрицы на поворот и сдвиг, но в отладке посмотрели значения, хранящиеся как в матрице поворота, так и в кватернионе, и всё честно - отсутствие поворота. Однако рисовалка начинает бешено вращать камеру, что неверно. Просьба разобраться.

**Comment by elevir** [comment]
@DaddyWesker единственное решение, которое я здесь вижу, это ограничение по количеству знаков после запятой. 6 знаков после запятой хватит? Или там выше точность?

**Comment by DaddyWesker** [comment]
точность там гораздо выше... Возможно стоит округлять до какого-то знака, но в любом случае непонятно, почему столь малые значения вызывают такие проблемы...

**Comment by elevir** [comment]
@DaddyWesker изменил немного способ нормировки кватерниона. Сборку сейчас пришлю. Нужно потестировать.

**Comment by elevir** [comment]
@DaddyWesker пока закрываю этот Issue в связи с выходом новой сборки. Если проблема снова проявится, то откройте пожалуйста заново этот Issue.
